# Generated by Django 5.2.2 on 2025-06-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='DreamKeyword',
        ),
        migrations.DeleteModel(
            name='DreamRecord',
        ),
    ]
